# Generated by Django 2.2.16 on 2022-10-06 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(blank=True, default=uuid.UUID('a78e3f25-6cc2-463f-aec3-cf80548da84e'), editable=False, null=True, unique=True),
        ),
    ]
