# Generated by Django 3.2.16 on 2022-10-05 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(blank=True, default=uuid.UUID('2b65eac0-765c-4b9f-a170-0915d2879fc3'), editable=False, null=True, unique=True),
        ),
    ]
