# Generated by Django 2.2.16 on 2022-10-06 12:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20221006_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(blank=True, default=uuid.UUID('d50b7441-2686-4cbb-a2ee-88aa54acba2e'), editable=False, null=True, unique=True),
        ),
    ]
