# Generated by Django 2.2.16 on 2022-10-06 14:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(blank=True, default=uuid.UUID('514aabb8-86f3-46f9-b3c3-4f5d06e64b30'), editable=False, null=True, unique=True),
        ),
    ]
