# Generated by Django 3.2.16 on 2022-10-06 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20221006_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(blank=True, default=uuid.UUID('d4c1aa69-ebb3-4bb1-8551-02a003e6344b'), editable=False, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username', 'confirmation_code'), name='unique_username_confirmation_code'),
        ),
    ]
