# Generated by Django 2.2.16 on 2022-10-06 17:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_auto_20221006_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(blank=True, default=uuid.UUID('5b7d50d9-8d4b-4df9-8ec3-e1c313bb1198'), editable=False, null=True, unique=True),
        ),
    ]
