# Generated by Django 2.2.16 on 2022-10-06 18:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_auto_20221006_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('1115adfa-2f80-4832-b3d2-ba789989eadf'), editable=False, unique=True),
        ),
    ]
