# Generated by Django 2.2.16 on 2022-10-06 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_auto_20221006_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('487d851a-1496-4df1-864d-afe3d0eab728'), editable=False),
        ),
    ]
