# Generated by Django 2.2.16 on 2022-10-08 05:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_auto_20221007_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('75b0241f-f3f4-4cc6-a272-6470aac021c8'), editable=False),
        ),
    ]
