# Generated by Django 2.2.16 on 2022-10-09 10:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0008_auto_20221008_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('de0ba664-abb5-4633-a304-147dc0604275'), editable=False),
        ),
    ]
