# Generated by Django 2.2.16 on 2022-10-08 11:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0017_auto_20221008_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='titles.Title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('5c816e4a-e5f1-40da-b63e-5b2acdf89650'), editable=False),
        ),
    ]
