# Generated by Django 2.2.16 on 2022-10-08 21:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0024_auto_20221009_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('9a4a467a-7039-4c40-b782-b25f1b00552e'), editable=False),
        ),
    ]
