# Generated by Django 2.2.16 on 2022-10-09 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0025_auto_20221009_0018'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review',
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('2380156b-62ae-4867-a4dd-0cd4b28c19f6'), editable=False),
        ),
    ]
