# Generated by Django 2.2.16 on 2022-10-09 13:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0033_auto_20221009_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='titles.Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('8ddac13a-ddeb-4e1e-b4b7-5d3da215ba5f'), editable=False),
        ),
    ]
