# Generated by Django 2.2.16 on 2022-10-09 22:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0047_auto_20221010_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('405ca626-fc44-4303-a273-fffa0c733b3c'), editable=False),
        ),
    ]
