# Generated by Django 2.2.16 on 2022-10-09 22:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0048_auto_20221010_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('e0f92b18-55ed-4537-a7b1-6d61effdd459'), editable=False),
        ),
    ]
