# Generated by Django 2.2.16 on 2022-10-12 12:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('704139e2-9d8e-41a8-9fc6-461b295e9f87'), editable=False),
        ),
    ]
