# Generated by Django 2.2.16 on 2022-10-10 19:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221010_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('162c066e-8847-4766-8679-0da8995a0599'), editable=False),
        ),
    ]
