# Generated by Django 2.2.16 on 2022-10-12 23:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221012_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('15dd8b5b-02ca-4022-9f25-f6fa11d88241'), editable=False),
        ),
    ]
