# Generated by Django 2.2.16 on 2022-10-10 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221010_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('22f7ae53-ff8e-4807-843d-acb0985a772e'), editable=False),
        ),
    ]
