# Generated by Django 2.2.16 on 2022-10-07 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_auto_20221007_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('2b97942e-ddd9-44a1-9240-e0fcf5bd844f'), editable=False),
        ),
    ]
