# Generated by Django 2.2.16 on 2022-10-10 19:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20221010_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.TitleRating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('9c111d90-c277-419d-9a7e-8d1f5867e631'), editable=False),
        ),
    ]
