# Generated by Django 2.2.16 on 2022-10-07 12:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_auto_20221007_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('45901f99-43fd-4655-922a-276aa8046048'), editable=False),
        ),
    ]
