# Generated by Django 2.2.16 on 2022-10-10 19:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20221010_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.TitleRating'),
        ),
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.TitleRating'),
        ),
        migrations.AlterField(
            model_name='titlerating',
            name='value',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('b19df653-cfed-443b-b143-c2dcd088ba3a'), editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='titlerating',
            unique_together={('user', 'value')},
        ),
        migrations.RemoveField(
            model_name='titlerating',
            name='title',
        ),
    ]
