# Generated by Django 2.2.16 on 2022-10-10 20:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20221010_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('817ffea7-47d3-4c51-92ec-41ef551a7881'), editable=False),
        ),
    ]
