# Generated by Django 2.2.16 on 2022-10-10 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20221010_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('67529a94-ecb9-470c-997e-f26ede7b612b'), editable=False),
        ),
    ]
