# Generated by Django 2.2.16 on 2022-10-08 10:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0011_auto_20221008_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('d79cfd67-e63c-41b8-ab61-5a11e9a5288a'), editable=False),
        ),
    ]
