# Generated by Django 2.2.16 on 2022-10-10 22:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20221010_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('41054a72-4771-47c7-b450-afadac26271b'), editable=False),
        ),
    ]
