# Generated by Django 2.2.16 on 2022-10-10 22:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20221011_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='reviews.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('ee245aa0-39b9-40b8-af65-2e44218975b3'), editable=False),
        ),
    ]
