# Generated by Django 2.2.16 on 2022-10-09 13:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0031_auto_20221009_1620'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_author_title',
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('7e46e188-8c16-40a6-ba39-221a3925338a'), editable=False),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author_id', 'title_id'), name='unique_author_title'),
        ),
    ]
