# Generated by Django 2.2.16 on 2022-10-09 19:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0046_auto_20221009_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('7e6db8c2-8d87-41d2-8a10-dd40770ea504'), editable=False),
        ),
    ]
