# Generated by Django 2.2.16 on 2022-10-10 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0049_auto_20221010_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('dbb87682-8416-4b17-85e3-aa38b830d99a'), editable=False),
        ),
    ]
