# Generated by Django 2.2.16 on 2022-10-10 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0050_auto_20221010_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('558830f0-c869-44c7-b3dd-9545fff830d0'), editable=False),
        ),
    ]
